-- ====================================================================================
-- MIGRACION: Crear tabla c_costo y relacionarla con ticket/cliente
-- Esquema objetivo: base_de_datos_csu
-- ====================================================================================

CREATE TABLE IF NOT EXISTS base_de_datos_csu.c_costo (
  id_c_costo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  descripcion TEXT,
  presupuesto NUMERIC(14,2) NOT NULL DEFAULT 0,
  costo_ejecutado NUMERIC(14,2) NOT NULL DEFAULT 0,
  estado VARCHAR(20) NOT NULL DEFAULT 'activo',
  fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  id_cliente INTEGER NOT NULL,
  CONSTRAINT fk_c_costo_cliente
    FOREIGN KEY (id_cliente)
    REFERENCES base_de_datos_csu.cliente(id_cliente)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT chk_c_costo_montos_no_negativos
    CHECK (presupuesto >= 0 AND costo_ejecutado >= 0),
  CONSTRAINT chk_c_costo_estado
    CHECK (estado IN ('activo', 'inactivo', 'cerrado'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_c_costo_codigo
  ON base_de_datos_csu.c_costo(codigo);

CREATE INDEX IF NOT EXISTS idx_c_costo_id_cliente
  ON base_de_datos_csu.c_costo(id_cliente);

ALTER TABLE base_de_datos_csu.ticket
  ADD COLUMN IF NOT EXISTS id_c_costo INTEGER;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_ticket_c_costo'
      AND connamespace = 'base_de_datos_csu'::regnamespace
  ) THEN
    ALTER TABLE base_de_datos_csu.ticket
      ADD CONSTRAINT fk_ticket_c_costo
      FOREIGN KEY (id_c_costo)
      REFERENCES base_de_datos_csu.c_costo(id_c_costo)
      ON UPDATE CASCADE
      ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_ticket_id_c_costo
  ON base_de_datos_csu.ticket(id_c_costo);
